version: "3.8"

networks:
  websites:
    external: true

services:
  nginx:
    container_name: wire_telecoms_landing-nginx
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wire_telecoms_landing.rule=Host(`www.towerco-analytics.com`)"
      - "traefik.http.routers.wire_telecoms_landing.entrypoints=websecure"
      - "traefik.http.routers.wire_telecoms_landing.tls.certresolver=myresolver"
      - "traefik.http.services.wire_telecoms_landing.loadbalancer.server.port=80"        
    restart: unless-stopped
    networks:
      - websites
